name: minigpt-crop

channels:
  - defaults

dependencies:
  - python=3.9
  - pip
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - accelerate==0.20.3
      - bitsandbytes==0.46.1
      - gradio==3.47.1
      - huggingface-hub==0.18.0
      - iopath==0.1.10
      - matplotlib==3.9.4
      - numpy==1.26.4
      - omegaconf==2.3.0
      - opencv-python==4.7.0.72
      - pandas==2.2.3
      - peft==0.2.0
      - pillow==10.4.0
      - psutil==7.2.2
      - pyyaml==6.0.3
      - regex==2026.1.15
      - sacremoses==0.1.1
      - scikit-image==0.24.0
      - sentencepiece==0.2.0
      - timm==0.6.13
      - tokenizers==0.13.2
      - tqdm==4.68.1
      - transformers==4.30.0
      - visual-genome==1.1.1
      - wandb==0.26.1
      - webdataset==0.2.48
      - decord==0.6.0
